name: push to lukebaxnet
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'main'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         name: id_rsa # optional
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: |
        git remote add lukebaxnet ssh://root@lukebax.net/var/repo/lukebaxnet.git
        git config --global user.email "luke.bax@talktalk.net"
        git config --global user.name "LukeBax101"
        git checkout main
        git push -u lukebaxnet main